name: mushrooms
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0

  backend:
    build:
      context: ./backend
    environment:
      - DJANGO_DEBUG=1
      - POSTGRES_DB=mushrooms
      - POSTGRES_USER=mushrooms
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=mushrooms
      - POSTGRES_USER=mushrooms
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
